
module.exports = {
  FILE_START: 'FILE_START',
  FILE_END: 'FILE_END',
  QUEUE_START: 'QUEUE_START',
  QUEUE_END: 'QUEUE_END',
  SUITE_START: 'SUITE_START',
  SUITE_END: 'SUITE_END',
  SUITE_SPLIT: 'SUITE_SPLIT',
  HOOK_START: 'HOOK_START',
  HOOK_END: 'HOOK_END',
  TEST_START: 'TEST_START',
  TEST_END: 'TEST_END',
};
